### ISSUE TITLE
'You are using 32-bit version of Firefox' when regular Firefox is not installed at all

### ISSUE THREAD

**Issue by eight04** [mozilla-jetpack/node-fx-runner#31]
I only have Developer Edition installed on my system:
```bat
> web-ext run
You are using 32-bit version of Firefox on 64-bit versions of the Windows.
Some features may not work correctly in this version. You should upgrade Firefox
 to the latest 64-bit version now!
Error: spawn C:\Program Files (x86)\Mozilla Firefox\firefox.exe ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
Here is the registry dump:
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla]

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Firefox]

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Firefox\Extensions]

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Firefox\TaskBarIDs]
"C:\\Program Files\\Firefox Developer Edition"="CA9422711AE1A81C"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Firefox Developer Edition]
@="56.0"
"CurrentVersion"="56.0 (x64 zh-TW)"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Firefox Developer Edition\56.0 (x64 zh-TW)]
@="56.0 (x64 zh-TW)"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Firefox Developer Edition\56.0 (x64 zh-TW)\Main]
"Install Directory"="C:\\Program Files\\Firefox Developer Edition"
"PathToExe"="C:\\Program Files\\Firefox Developer Edition\\firefox.exe"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Firefox Developer Edition\56.0 (x64 zh-TW)\Uninstall]
"Description"="Firefox Developer Edition 56.0 (x64 zh-TW)"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Firefox Developer Edition 56.0]
"GeckoVer"="56.0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Firefox Developer Edition 56.0\bin]
"PathToExe"="C:\\Program Files\\Firefox Developer Edition\\firefox.exe"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Firefox Developer Edition 56.0\extensions]
"Components"="C:\\Program Files\\Firefox Developer Edition\\components"
"Plugins"="C:\\Program Files\\Firefox Developer Edition\\plugins"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\MaintenanceService]
"Attempted"=dword:00000001
"Installed"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\MaintenanceService\5af7e3254c94d35f13dcf43d6f519f62]

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\MaintenanceService\5af7e3254c94d35f13dcf43d6f519f62\0]
"name"="Mozilla Corporation"
"issuer"="DigiCert SHA2 Assured ID Code Signing CA"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\MaintenanceService\5af7e3254c94d35f13dcf43d6f519f62\1]
"name"="Mozilla Corporation"
"issuer"="DigiCert Assured ID Code Signing CA-1"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Thunderbird]

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Thunderbird\Extensions]

```
We should only display that error message if:

1. 32-bit version Firefox is installed
2. Can't find 64-bit version of Firefox

**Comment by kumar303** [comment]
Thanks for all the info @eight04 

@Standard8 may want to follow this issue.

**Comment by birtles** [comment]
I likewise see this on a completely fresh install of Windows with only Nightly (64-bit) installed.

**Comment by birtles** [comment]
Sorry, my bad. It's precisely because I only have Nightly installed.
